version: "3.5"

services:
  orthanc-server:
    container_name: orthanc-server
    build:
      context: ./
      dockerfile: Dockerfile
    image: dentalray/orthanc-server
    volumes:
      - ./config:/etc/orthanc/
      - ./logs/orthanc:/var/log/orthanc/
      - ./logs/postgresql:/var/log/postgresql
      - ./storage:/OrthancStorage
    ports:
      - 4242:4242
      - 8042:8042
    networks:
      - orthanc-server-network
networks:
  orthanc-server-network:
    name: orthanc-server-network
    driver: bridge